# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_data',
            field=models.BinaryField(),
        ),
    ]
