# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webterp', '0002_auto_20160331_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_data', models.BinaryField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webterp.Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
